image: Visual Studio 2017

init:
- git config --global core.autocrlf input
- ps: $env:Path += ";C:\Program Files\PostgreSQL\9.6\bin\"

skip_branch_with_pr: true
skip_tags: true
skip_commits:
  files:
    - '**/*.md'

environment:
  Appveyor: true
  MYSQL_ENV_MYSQL_USER: root
  MYSQL_ENV_MYSQL_PASSWORD: Password12!
  PGUSER: postgres
  PGPASSWORD: Password12!
  MYSQL_PWD: Password12!
services:
- mssql2016
- mysql
- postgresql

nuget:
  disable_publish_on_pr: true

build_script:
  # Postgres
  - createdb test
  # MySQL
  - mysql -e "create database test;" --user=root
  # Our stuff
  - ps: .\build.ps1 -BuildNumber "$env:APPVEYOR_BUILD_NUMBER" -Version "$env:APPVEYOR_REPO_TAG_NAME" -PullRequestNumber "$env:APPVEYOR_PULL_REQUEST_NUMBER" -CreatePackages $true

test: off
artifacts:
- path: .\.nupkgs\*.nupkg
  
#deploy:
#- provider: NuGet
#  server: https://www.myget.org/F/stackoverflow/api/v2
#  on:
#    branch: master  
#  api_key:
#    secure: P/UHxq2DEs0GI1SoDXDesHjRVsSVgdywz5vmsnhFQQY5aJgO3kP+QfhwfhXz19Rw
#  symbol_server: https://www.myget.org/F/stackoverflow/symbols/api/v2/package